Models/DiscountViewModel.cs
namespace AzureQueueSt.Models
{
    public class DiscountViewModel
    {
        public string? Message { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace AzureQueueSt.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using AzureQueueSt.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AzureQueueSt.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/QueueController.cs
using AzureQueueSt.Models;
using AzureQueueSt.Services.Abstracts;
using Microsoft.AspNetCore.Mvc;

namespace AzureQueueSt.Controllers
{
    public class QueueController : Controller
    {

        private readonly IQueueService _queueService;
        private readonly IDiscountQueueService _discountQueueService;
        public QueueController(IQueueService queueService, IDiscountQueueService discountQueueService)
        {
            _queueService = queueService;
            _discountQueueService = discountQueueService;
        }
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> SendDiscount()
        {
            var vm = new DiscountViewModel
            {
                Message = null
            };
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> SendDiscount(DiscountViewModel vm)
        {
            await _discountQueueService.SendMessageAsync(vm.Message);
            return View("Index");
        }

        [HttpGet]
        public async Task<IActionResult> ReceiveDiscount()
        {
            var message = await _discountQueueService.ReceiveMessageAsync();

            if (message == null)
            {
                message = "No discount yet";
            }
            return View("Index",message);
            
        }

        [HttpPost("send")]
        public async Task<IActionResult> SendMessage([FromBody] string message)
        {
            await _queueService.SendMessageAsync(message);
            return Ok("Message added to queue succesfully!");
        }

        [HttpGet("receive")]
        public async Task<IActionResult> ReceiveMessage()
        {
            var message = await _queueService.ReceiveMessageAsync();
            if (message != null)
            {
                return Ok($"Result Message : {message}");
            }
            return NotFound("No message found in queue!");
        }
    }
}

Views/Queue/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model string 

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div>

    <h1>@Model</h1>

    <a href="/Queue/SendDiscount">Generate Discount</a>
    <a href="/Queue/ReceiveDiscount">Show Discount</a>
</div>

Views/Queue/SendDiscount.cshtml
@model DiscountViewModel

<form asp-action="SendDiscount" asp-controller="Queue" method="post">
    <input asp-for="Message" type="text" placeholder="Enter discount" />
    
    <button type="submit">Create Discount</button>

</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AzureQueueSt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AzureQueueSt.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AzureQueueSt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AzureQueueSt - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>